// Runs on every Netlify build: copies [difficulty, answer] for each question from index.html
// so the server can score the Daily 10. Add questions to index.html only; this keeps them in sync.
import { readFileSync, writeFileSync } from "node:fs";
const html = readFileSync("public/index.html", "utf8");
const js = html.split("<script>")[1].split("</script>")[0];
const RAW = new Function(js.split("const SPORTS")[0] + ";return RAW;")();
writeFileSync("netlify/lib/bank.mjs", "// Generated by scripts/gen-bank.mjs. [difficulty, correct answer] in bank order.\nexport default " + JSON.stringify(RAW.map(r => [r[2], r[4]])) + ";\n");
console.log("Daily bank synced:", RAW.length, "questions");
